CREATE OR REPLACE TABLE COLUMNSPECIFICATION (
	PROCESS_ID NUMBER(38,0) NOT NULL,
	PROCESS_NAME VARCHAR(16777216) NOT NULL,
	FILE_NAME_PATTERN VARCHAR(16777216) NOT NULL,
	COL_SPECS VARCHAR(16777216) NOT NULL,
	SKIP_ROWS NUMBER(38,0),
	COLUMN_NAMES VARCHAR(16777216)
)COMMENT='DEFINE THE COLUMN SPECIFICATION FOR A FILE'
;

CREATE OR REPLACE TABLE CONNECTIONDATA (
	CONNECTION_ID NUMBER(10,0) NOT NULL,
	CONNECTION_NAME VARCHAR(255) NOT NULL,
	CONNECTION_STR VARIANT NOT NULL,
	CREATED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	MODIFIED_DATE TIMESTAMP_LTZ(3),
	CONSTRAINT CONNECTIONDATA_PK PRIMARY KEY (CONNECTION_ID)
)COMMENT='CONFIG'
;

CREATE OR REPLACE TABLE ETL_ERROR (
	ERROR_ID NUMBER(10,0) NOT NULL AUTOINCREMENT,
	RUN_ID NUMBER(10,0),
	PROCESS_ID NUMBER(10,0) NOT NULL,
	ERROR_DESC VARCHAR(2000),
	ERROR_LINE VARCHAR(100),
	ERROR_CODE NUMBER(10,0),
	ERROR_COL VARCHAR(2000),
	CREATED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	MODIFIED_DATE TIMESTAMP_LTZ(3),
	CONSTRAINT ETL_ERROR_PK PRIMARY KEY (ERROR_ID)
);

CREATE OR REPLACE TABLE ETL_NOTIFICATION_ALERT (
	NOTIFICATION_ID NUMBER(10,0) NOT NULL,
	PROCESS_ID NUMBER(10,0) NOT NULL,
	NOTIFICATION VARCHAR(2000),
	SENDER VARCHAR(255),
	RECIPIENT VARCHAR(255),
	STATUS VARCHAR(255),
	CREATED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	MODIFIED_DATE TIMESTAMP_LTZ(3),
	CONSTRAINT ETL_NOTIFICATION_ALERT_PK PRIMARY KEY (NOTIFICATION_ID)
)COMMENT='CONFIG'
;

CREATE OR REPLACE TABLE ETL_PROCEDURE (
	PROCEDURE_ID NUMBER(10,0) NOT NULL,
	SQL_PROCEDURE VARCHAR(5000) NOT NULL,
	TGT_TABLE VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	MODIFIED_DATE TIMESTAMP_LTZ(3),
	CONSTRAINT ETL_PROCEDURE_PK PRIMARY KEY (PROCEDURE_ID)
)COMMENT='CONFIG'
;

CREATE OR REPLACE TABLE ETL_PROCESS (
	RUN_ID NUMBER(10,0) NOT NULL AUTOINCREMENT,
	PROCESS_ID NUMBER(10,0) NOT NULL,
	PROCESS_NAME VARCHAR(255),
	CUSTODIAN_NAME VARCHAR(255) NOT NULL,
	SRC_FILE_TABLE_NAME VARCHAR(255) NOT NULL,
	FILE_TYPE VARCHAR(255) NOT NULL,
	TGT_TABLE VARCHAR(255) NOT NULL,
	LOAD_TYPE VARCHAR(255) NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	TOTAL_RECORD_COUNT NUMBER(10,0) NOT NULL,
	RECORDS_LOADED NUMBER(10,0),
	RECORDS_REJECTED NUMBER(10,0),
	STATUS VARCHAR(255) NOT NULL,
	FILE_DATE DATE,
	CREATED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	MODIFIED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	CONSTRAINT ETL_PROCESS_PK PRIMARY KEY (PROCESS_ID)
);

CREATE OR REPLACE TABLE ETL_TRANSFORMATION_RULES (
	RULE_ID NUMBER(10,0) NOT NULL,
	SRC_TABLE VARCHAR(255) NOT NULL,
	SRC_COLUMN VARCHAR(255),
	RULE VARCHAR(255),
	SQL_QUERY VARCHAR(2000),
	TGT_COLUMN VARCHAR(255) NOT NULL,
	TGT_TABLE VARCHAR(255) NOT NULL,
	DEFAULT_VALUE VARCHAR(255),
	CREATED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	MODIFIED_DATE TIMESTAMP_LTZ(3),
	CONSTRAINT ETL_TRANSFORMATION_RULES_PK PRIMARY KEY (RULE_ID)
)COMMENT='CONFIG'
;

CREATE OR REPLACE TABLE FILELOCATION (
	FILELOCATION_ID NUMBER(10,0) NOT NULL,
	PROCESS_ID NUMBER(10,0) NOT NULL,
	LOCAL_FOLDER VARCHAR(255) NOT NULL,
	ARCHIVE_FOLDER VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	MODIFIED_DATE TIMESTAMP_LTZ(3),
	CONSTRAINT FILELOCATION_PK PRIMARY KEY (FILELOCATION_ID)
)COMMENT='CONFIG'
;

CREATE OR REPLACE TABLE TABLE_MAPPING (
	PROCESS_ID NUMBER(10,0) NOT NULL,
	PROCESS_NAME VARCHAR(10) NOT NULL,
	LOAD_TYPE VARCHAR(20) NOT NULL,
	MAPPING_DICT VARIANT NOT NULL,
	CREATED_DATE TIMESTAMP_LTZ(3) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_LTZ(3)),
	MODIFIED_DATE TIMESTAMP_LTZ(3)
)COMMENT='CONFIG'
;
